export * from './ICompany';
export * from './ICompanyDetail';
export * from './ICompanyList';
export * from './ICustomer';
export * from './ICustomerDetail';
export * from './ICustomerList';
export * from './IRole';
export * from './IRoleDetail';
export * from './IRoleList';