import { IEmployeeBank, IEmployeeContact } from '@account/classes/response';
import { ICommonSystem } from '@common/classes';
import { IBaseChanges } from '@generic/interfaces/IBaseChanges';
import { ILookupCompany } from '@lookup/classes';

export interface IEmployeeDetail {
    uid: string;
    joinDate: string;
    inactiveDate?: string;
    companyUid?: string;
    company?: ILookupCompany;
    employmentNumber: string;
    employmentType: string;
    employment?: ICommonSystem;
    fullName: string;
    dateOfBirth?: string;
    birthPlace?: string;
    email: string;
    emailPersonal?: string ;
    phone?: string;
    mobilePhone?: string;
    address?: string ;
    addressAdditional?: string;
    genderType?: string;
    gender?: ICommonSystem;
    religionType?: string;
    religion?: ICommonSystem;
    taxType?: string;
    tax?: ICommonSystem;
    bloodType?: string;
    blood?: ICommonSystem;
    familyCardNumber?: string;
    citizenNumber?: string;
    taxNumber?: string;
    bpjsEmploymentNumber?: string;
    bpjsHealthCareNumber?: string;
    bank?: IEmployeeBank;
    contact?: IEmployeeContact;
    image?: FileList;
    changes?: IBaseChanges;
}