export * from './ICustomerAllRequest';
export * from './ICustomerByIdRequest';
export * from './ICustomerListRequest';
export * from './IMenuListRequest';
export * from './IMenuAllRequest';
export * from './IMenuByIdRequest';
export * from './IPositionListRequest';
export * from './IPositionAllRequest';
export * from './IPositionByIdRequest';