export * from './ICustomerAllRequest';
export * from './ICustomerByIdRequest';
export * from './ICustomerListRequest';
export * from './IRoleAllRequest';
export * from './IRoleByIdRequest';
export * from './IRoleListRequest';
export * from './ICompanyAllRequest';
export * from './ICompanyByIdRequest';
export * from './ICompanyListRequest';