export * from './ICustomerAllRequest';
export * from './ICustomerByIdRequest';
export * from './ICustomerListRequest';
export * from './IMenuListRequest';
export * from './IMenuGetAllRequest';
export * from './IMenuByIdRequest';
export * from './IPositionListRequest';
export * from './IPositionGetAllRequest';
export * from './IPositionByIdRequest';